_target_: src.datamodules.fake_news_data.MultiModalData

img_path: /data/fake_news/datasets/MM17-WeiboRumorSet/images
dataset_name: weibo
tokenizer_name: bert-base-chinese
processor_name: null
train_path: /data/fake_news/datasets/MM17-WeiboRumorSet/train_data.json
test_path: /data/fake_news/datasets/MM17-WeiboRumorSet/test_data.json
max_length: 200
val_set_ratio: 0.1
batch_size: 32
num_workers: 0
