# docker-image.yml
name: Publish Docker image # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow

on:
  push:
    branches:
      - "main"
    paths:
      - "requirements.txt"

jobs: # workflow中的job
  push_to_registry: # job的名字
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # job运行的基础环境

    steps: # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3 # 官方的action，获取代码

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: anbinx/nv-torch-env
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
